typography_spectrum: 0.4318080134689808
color:
  brandStrength: 0.5030672319699079
  lightness: 0.4171042125672102
  saturation: 0.43335546599701047
  rhythmicContrast: 0.4082125669810921
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
layout_spectrum: 0.9866530823055655
name: rejuvi results skin clinic
navigation:
  - name: getting to know us....
    url: 'http://rejuviresults.com.au'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d09f7de7-eb20-4979-ad6c-586b368e3033.png
title: recapture the beauty of self-confidence
