typography_spectrum: 0.5965255449991673
color:
  brandStrength: 0.29386655683629215
  lightness: 0.34740073163993657
  saturation: 0.646064639557153
  rhythmicContrast: 0.5056144923437387
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
layout_spectrum: 0.6738070447463542
name: rejuvi results skin clinic
navigation:
  - name: getting to know us....
    url: 'http://rejuviresults.com.au'
    type: external
title: recapture the beauty of self-confidence
